name: samtools fastq separate
description:
  Convert a bam file with paired end reads back to unaligned reads into 
  separate fastq files with `samtools`. Reads that are secondary (0x100) and
  supplementary reads (0x800) are discarded.
authors:
  - Alexander Hübner
notes: |
  * The `extra` param allows for additional program arguments.
  * For more information see, http://www.htslib.org/doc/samtools-fasta.html
